# Copyright (C) 2025  <Yijiu Zhao>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

import qrcode
import os

def create_qr_code(data, filename):    
# 创建QRCode对象    
    qr = qrcode.QRCode(      
        version = 1,  # 控制二维码的大小，1是最小的，40是最大的        
        error_correction=qrcode.constants.ERROR_CORRECT_L,  # 控制二维码的错误纠正级别        
        box_size = 10,  # 控制二维码中每个小格子的大小        
        border = 4,  # 控制边框的宽度（默认为4，也是最小值）    
    )    
# 添加数据到QRCode对象    
    qr.add_data(data)    
    qr.make(fit=True)    
# 创建图像并保存    
    img = qr.make_image(fill_color="black", back_color="white")   
    path = os.path.join(os.path.dirname(__file__),'images','QR', filename)
    img.save(path)# 使用函数
    print(f"QR code has been saved as {filename}")

data = "QR generated by Python"  
filename = "example_qr.png"  
# 输出文件名
# create_qr_code(data, filename)
# 